#version: '2'
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2281:2181"
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_BROKER_ID: 1
##      KAFKA_CREATE_TOPICS: "test:1:1"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#
#

version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2281:2181"
    environment:
      zk_id: "1"
  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
